services:
  - type: web
    name: hornerito-bot
    env: node
    buildCommand: |
      npm install
      cd v0.0.1-dashboard
      npm install tailwindcss lucide-react date-fns recharts @radix-ui/react-dialog @radix-ui/react-dropdown-menu @radix-ui/react-slot @radix-ui/react-toast
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false 